name: 'slack-notify'

inputs:
  status:
    required: false
    default: 'failure'
  slack_incoming_url:
    required: true

runs:
  using: 'composite'

  steps:
    - name: Send slack
      shell: bash
      run: |
        if [ "${{ inputs.status }}" = "success" ]; then
          EMOTICON="✅"
        else
          EMOTICON="⛔"
        fi
        
        MSG="{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<https://github.com/${GITHUB_REPOSITORY}|${GITHUB_REPOSITORY}>haveanewdeploy:\\n*result=>${EMOTICON}*\"}},{\"type\":\"actions\",\"elements\":[{\"type\":\"button\",\"text\":{\"type\":\"plain_text\",\"emoji\":true,\"text\":\"확인\"},\"style\":\"primary\",\"value\":\"click_me_123\",\"url\":\"https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}/checks|${GITHUB_JOB}\"}]}]}"

        curl -X POST -H 'Content-type: application/json' --data "${MSG}" "${{ inputs.slack_incoming_url }}"


